[package]
name = "steg-playground"
version = "0.1.21"
edition = "2024"

[dependencies]
noise = { version = "0.9.0", features = ["images"] }
rand = "0.9.1"
image = "0.25.6"
rand_xoshiro = "0.7.0"
bitvec = "1.0.1"